# Generated by Django 5.2.5 on 2025-08-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('futbol', models.CharField(max_length=20)),
                ('tenis', models.CharField(max_length=20)),
                ('padel', models.CharField(max_length=20)),
            ],
        ),
    ]
