# Generated by Django 5.2.5 on 2025-08-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('indumentaria', models.CharField(max_length=20)),
            ],
        ),
    ]
